<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DNAQMSAPI.Application\DNAQMSAPI.Application.csproj" />
    <ProjectReference Include="..\DNAQMSAPI.Domain\DNAQMSAPI.Domain.csproj" />
    <ProjectReference Include="..\..\AntiGravity.Enterprise.Shared.Core\AntiGravity.Enterprise.Shared.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="MySql.Data" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

