<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Microsoft.AspNetCore & Core Libraries -->
    <PackageVersion Include="Asp.Versioning.Mvc" Version="8.1.1" />
    <PackageVersion Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.19" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="8.0.19" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.3" />
    <PackageVersion Include="MySqlConnector" Version="2.5.0" />
    <PackageVersion Include="SkiaSharp" Version="2.88.8" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Win32" Version="2.88.8" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="4.0.0" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
    <!-- OpenApi / Swagger -->
    <PackageVersion Include="Microsoft.OpenApi" Version="1.6.14" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <!-- Dapper / Data Access -->
    <PackageVersion Include="Dapper" Version="2.1.66" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.3" />
    <PackageVersion Include="MongoDB.Driver" Version="3.6.0" />
    <PackageVersion Include="MySql.Data" Version="9.0.0" />
    <PackageVersion Include="Oracle.ManagedDataAccess.Core" Version="23.26.100" />
    <!-- Logging -->
    <PackageVersion Include="NLog.Database" Version="6.0.3" />
    <PackageVersion Include="NLog.Web.AspNetCore" Version="6.1.1" />
    <!-- Utilities -->
    <PackageVersion Include="MailKit" Version="4.15.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
</Project>