using System;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using DNAQMSAPI.Application.InvoiceGeneration.DTOs;
using DNAQMSAPI.Application.InvoiceGeneration.Interfaces;
using DNAQMSAPI.Application.Interfaces;
using Microsoft.Extensions.Logging;
using System.Linq;

namespace DNAQMSAPI.Infrastructure.InvoiceGeneration.Services;

public class InvoiceService : IInvoiceService
{
    private readonly IDapperDBFactory _dbFactory;
    private readonly ILogger<InvoiceService> _logger;

    public InvoiceService(IDapperDBFactory dbFactory, ILogger<InvoiceService> logger)
    {
        _dbFactory = dbFactory;
        _logger = logger;
    }

    public async Task<InvoiceModel?> GetInvoiceDetailsAsync(Guid invoiceId, CancellationToken cancellationToken = default)
    {
        var result = await _dbFactory.QueryAsync<InvoiceModel>(
            "PR_S_InvoiceDetails",
            new { p_InvoiceId = invoiceId.ToString() },
            commandType: CommandType.StoredProcedure);

        return result.FirstOrDefault();
    }

    public async Task<string> GetInvoiceHtmlAsync(Guid invoiceId, CancellationToken cancellationToken = default)
    {
        var invoice = await GetInvoiceDetailsAsync(invoiceId, cancellationToken);
        if (invoice == null) return "<h1>Invoice Not Found</h1>";

        var html = $@"
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; padding: 20px; }}
                .invoice-box {{ max-width: 800px; margin: auto; padding: 30px; border: 1px solid #eee; box-shadow: 0 0 10px rgba(0, 0, 0, .15); }}
                .header {{ display: flex; justify-content: space-between; border-bottom: 1px solid #eee; padding-bottom: 20px; }}
                .details {{ margin-top: 20px; display: flex; justify-content: space-between; }}
                table {{ width: 100%; text-align: left; margin-top: 20px; border-collapse: collapse; }}
                table th, table td {{ padding: 10px; border-bottom: 1px solid #eee; }}
                .totals {{ margin-top: 20px; text-align: right; }}
            </style>
        </head>
        <body>
            <div class='invoice-box'>
                <div class='header'>
                    <div>
                        <h2>ENTERPRISE INVOICE</h2>
                        <p>Tenant VAT: {invoice.TenantVatNumber ?? "N/A"}</p>
                    </div>
                    <div>
                        <p><strong>Invoice ID:</strong> {invoice.InvoiceId}</p>
                        <p><strong>Date:</strong> {invoice.BillingDate:yyyy-MM-dd}</p>
                    </div>
                </div>
                <div class='details'>
                    <div>
                        <strong>Billed To:</strong><br>
                        Subscription: {invoice.SubscriptionId}<br>
                        Customer VAT: {invoice.CustomerVatNumber ?? "N/A"}<br>
                        Reverse Charge: {(invoice.IsReverseCharge ? "YES" : "NO")}
                    </div>
                </div>
                <table>
                    <tr>
                        <th>Description</th>
                        <th>Amount</th>
                    </tr>
                    <tr>
                        <td>Subscription SaaS Fee</td>
                        <td>${invoice.NetAmount:F2}</td>
                    </tr>
                    <tr>
                        <td>Tax (VAT/GST)</td>
                        <td>${invoice.TotalTax:F2}</td>
                    </tr>
                </table>
                <div class='totals'>
                    <h3>Total Gross Amount: ${invoice.GrossAmount:F2}</h3>
                </div>
                <div style='margin-top:40px; font-size:12px; color:#777;'>
                    <p>Country Specific Meta: {invoice.CountrySpecificData ?? "{}"}</p>
                    <p>Generated by DNAQMS API - Phase 15 Compliance Engine</p>
                </div>
            </div>
        </body>
        </html>";

        return html;
    }
}
